### PR TITLE
version 0.3

### PR DESCRIPTION
**Pull request by HreYang**
Add function wrapper to ittnotify api functions.

### CODE REVIEW

**Comment by HreYang** [comment]
Update to version 0.5.
Modification files: libvtune.cc libvtune.h vtuneapi.cc

**Comment by TianyouLi** [comment]
Could you please make a single patch in a new branch and create a new pull request only contains one commit?? That will make my review easier.

**Comment by TianyouLi** [comment]
Coudl you please create one single patch in your branch and create one pull request with that one single patch? That will make my review easier.

**Comment by HreYang** [comment]
Hi Tianyou,

I have sent it again.
Attached is my simple example JS code.

Best regards,
Hre

**Pull request closed without merging**
